// @ts-nocheck
import { NextRequest, NextResponse } from "next/server";
import { getToken } from "next-auth/jwt";
import { getSpotifyClient } from "@/lib/spotify";

export async function POST(request: NextRequest) {
  try {
    const token = await getToken({ req: request as any, secret: process.env.NEXTAUTH_SECRET });

    if (!token || !token.accessToken) {
      return NextResponse.json(
        { error: "Unauthorized - Please log in with Spotify" },
        { status: 401 }
      );
    }

    // Check for token refresh errors
    if (token.error === "RefreshAccessTokenError") {
      return NextResponse.json(
        { error: "Failed to refresh access token. Please log in again." },
        { status: 401 }
      );
    }

    const accessToken = token.accessToken as string;

    // Parse request body
    const body = await request.json();
    const { name, description, trackIds, isPublic = true } = body;

    // Validate required fields
    if (!name || typeof name !== "string") {
      return NextResponse.json(
        { error: "Playlist name is required" },
        { status: 400 }
      );
    }

    if (!trackIds || !Array.isArray(trackIds) || trackIds.length === 0) {
      return NextResponse.json(
        { error: "At least one track ID is required" },
        { status: 400 }
      );
    }

    if (trackIds.length > 100) {
      return NextResponse.json(
        { error: "Maximum 100 tracks allowed per playlist creation" },
        { status: 400 }
      );
    }

    console.log(`Creating playlist "${name}" with ${trackIds.length} tracks...`);
    console.log(`Access token starts with: ${accessToken.substring(0, 20)}...`);
    console.log(`Token scopes:`, token.scope);

    // Initialize Spotify client
    const spotify = getSpotifyClient(accessToken);

    // First, get the current user's Spotify ID
    const userProfile = await spotify.getMe();
    const userId = userProfile.body.id;
    console.log(`User ID: ${userId}`);

    // Create playlist using direct API call to have more control
    const createPlaylistResponse = await fetch(
      `https://api.spotify.com/v1/users/${userId}/playlists`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: name,
          description: description || `Personalized recommendations generated by Unheard Spotipy on ${new Date().toLocaleDateString()}`,
          public: isPublic,
        }),
      }
    );

    if (!createPlaylistResponse.ok) {
      const errorData = await createPlaylistResponse.json();
      console.error(`Failed to create playlist:`, errorData);
      throw new Error(`Failed to create playlist: ${createPlaylistResponse.status}`);
    }

    const playlistData = await createPlaylistResponse.json();

    const playlistId = playlistData.id;
    const playlistUrl = playlistData.external_urls.spotify;

    console.log(`Playlist created: ${playlistId}`);

    // Add tracks to the playlist in smaller batches
    // Format track IDs as Spotify URIs
    const trackUris = trackIds.map((id) => `spotify:track:${id}`);

    console.log(`Adding ${trackUris.length} tracks to playlist ${playlistId} in small batches...`);
    console.log(`First few track URIs: ${trackUris.slice(0, 3).join(", ")}`);
    console.log(`Playlist owner: ${playlistData.owner.id}, Current user: ${userId}`);

    // Try using the spotify-web-api-node library instead of fetch
    // Sometimes the library handles edge cases better than raw fetch
    console.log('Attempting to add tracks using spotify-web-api-node library...');

    try {
      // Split into small batches
      const BATCH_SIZE = 10;
      let totalAdded = 0;

      for (let i = 0; i < trackUris.length; i += BATCH_SIZE) {
        const batch = trackUris.slice(i, i + BATCH_SIZE);
        console.log(`Adding batch ${Math.floor(i/BATCH_SIZE) + 1} (${batch.length} tracks)...`);

        try {
          const result = await spotify.addTracksToPlaylist(playlistId, batch);
          totalAdded += batch.length;
          console.log(`Batch ${Math.floor(i/BATCH_SIZE) + 1} success. Snapshot: ${result.body.snapshot_id}`);

          // Small delay between batches
          if (i + BATCH_SIZE < trackUris.length) {
            await new Promise(resolve => setTimeout(resolve, 300));
          }
        } catch (batchError: any) {
          console.error(`Batch ${Math.floor(i/BATCH_SIZE) + 1} failed:`, {
            statusCode: batchError.statusCode,
            message: batchError.message,
            body: batchError.body
          });
          throw batchError;
        }
      }

      console.log(`Successfully added all ${totalAdded} tracks to playlist`);
    } catch (addError: any) {
      console.error(`Error adding tracks with library:`, addError);
      console.error(`Error details:`, {
        statusCode: addError.statusCode,
        message: addError.message,
        body: addError.body
      });
      throw addError;
    }

    return NextResponse.json(
      {
        success: true,
        playlist: {
          id: playlistId,
          name: playlistData.name,
          url: playlistUrl,
          trackCount: totalAdded,
        },
      },
      { status: 201 }
    );
  } catch (error: any) {
    console.error("Error creating playlist:", error);

    // Handle Spotify API errors
    if (error.statusCode === 401) {
      return NextResponse.json(
        { error: "Spotify authentication failed. Please log in again." },
        { status: 401 }
      );
    }

    if (error.statusCode === 403) {
      return NextResponse.json(
        { error: "Insufficient permissions to create playlist. Please sign out and sign back in to grant playlist creation permissions." },
        { status: 403 }
      );
    }

    if (error.statusCode === 429) {
      return NextResponse.json(
        { error: "Rate limit exceeded. Please try again in a few moments." },
        { status: 429 }
      );
    }

    return NextResponse.json(
      {
        error: "Failed to create playlist",
        details: error.message,
      },
      { status: 500 }
    );
  }
}